import Route from '@ioc:Adonis/Core/Route'
Route.post('/ex1', 'Lista2sController.ex1') 
Route.post('/ex2', 'Lista2sController.ex2') 
Route.post('/ex3', 'Lista2sController.ex3') 
Route.post('/ex4', 'Lista2sController.ex4') 
Route.post('/ex5', 'Lista2sController.ex5') 
Route.post('/ex6', 'Lista2sController.ex6') 
Route.post('/ex7', 'Lista2sController.ex7') 
Route.post('/ex8', 'Lista2sController.ex8') 
Route.post('/ex9', 'Lista2sController.ex9')